const fs = require('fs');
const path = require('path');

const servicesDir = path.join(__dirname, '../src/pages/services');
const outputFile = path.join(__dirname, '../src/data/autoGeneratedServices.js');

try {
  // Read all .jsx and .js files from services directory
  const files = fs.readdirSync(servicesDir)
    .filter(file => file.endsWith('.jsx') || file.endsWith('.js'))
    .map(file => file.replace(/\.(jsx|js)$/, ''))
    .sort();

  // Generate the JavaScript file with all services
  const content = `// ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated by running: npm run generate:services
// Run this command whenever you add new service pages

export const autoGeneratedServices = ${JSON.stringify(files, null, 2)};
`;

  fs.writeFileSync(outputFile, content);
  console.log(`✅ Successfully generated ${files.length} services`);
  console.log(`📁 File saved to: src/data/autoGeneratedServices.js`);
} catch (error) {
  console.error('❌ Error generating services list:', error.message);
  process.exit(1);
}
